//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.WebHelper
{
    using System.Web.Mvc;
    using UQing.Hr.IServices;
    /// <summary>
    /// 控制器的父类，将来被此网站的所有控制器继承
    /// </summary>
    public partial class BaseController : Controller
    {
        //1.0 定义当前系统中所有的业务逻辑层的接口成员
        protected Iqs_applyifoServices _qs_applyifoServices;
        protected Iqs_applyinfoServices _qs_applyinfoServices;
        protected Iuqinger_adServices _uqinger_adServices;
        protected Iuqinger_ad_categoryServices _uqinger_ad_categoryServices;
        protected Iuqinger_adminServices _uqinger_adminServices;
        protected Iuqinger_admin_auth_groupServices _uqinger_admin_auth_groupServices;
        protected Iuqinger_admin_logServices _uqinger_admin_logServices;
        protected Iuqinger_admin_roleServices _uqinger_admin_roleServices;
        protected Iuqinger_applyServices _uqinger_applyServices;
        protected Iuqinger_applyinfoServices _uqinger_applyinfoServices;
        protected Iuqinger_articleServices _uqinger_articleServices;
        protected Iuqinger_article_categoryServices _uqinger_article_categoryServices;
        protected Iuqinger_article_propertyServices _uqinger_article_propertyServices;
        protected Iuqinger_audit_reasonServices _uqinger_audit_reasonServices;
        protected Iuqinger_badwordServices _uqinger_badwordServices;
        protected Iuqinger_baidu_submiturlServices _uqinger_baidu_submiturlServices;
        protected Iuqinger_baiduxmlServices _uqinger_baiduxmlServices;
        protected Iuqinger_categoryServices _uqinger_categoryServices;
        protected Iuqinger_category_districtServices _uqinger_category_districtServices;
        protected Iuqinger_category_groupServices _uqinger_category_groupServices;
        protected Iuqinger_category_jobsServices _uqinger_category_jobsServices;
        protected Iuqinger_category_majorServices _uqinger_category_majorServices;
        protected Iuqinger_company_down_resumeServices _uqinger_company_down_resumeServices;
        protected Iuqinger_company_favoritesServices _uqinger_company_favoritesServices;
        protected Iuqinger_company_imgServices _uqinger_company_imgServices;
        protected Iuqinger_company_interviewServices _uqinger_company_interviewServices;
        protected Iuqinger_company_praiseServices _uqinger_company_praiseServices;
        protected Iuqinger_company_profileServices _uqinger_company_profileServices;
        protected Iuqinger_company_statisticsServices _uqinger_company_statisticsServices;
        protected Iuqinger_company_tplServices _uqinger_company_tplServices;
        protected Iuqinger_configServices _uqinger_configServices;
        protected Iuqinger_consultantServices _uqinger_consultantServices;
        protected Iuqinger_consultant_complaintServices _uqinger_consultant_complaintServices;
        protected Iuqinger_cronsServices _uqinger_cronsServices;
        protected Iuqinger_explainServices _uqinger_explainServices;
        protected Iuqinger_explain_categoryServices _uqinger_explain_categoryServices;
        protected Iuqinger_feedbackServices _uqinger_feedbackServices;
        protected Iuqinger_helpServices _uqinger_helpServices;
        protected Iuqinger_help_categoryServices _uqinger_help_categoryServices;
        protected Iuqinger_hotwordServices _uqinger_hotwordServices;
        protected Iuqinger_hrtoolsServices _uqinger_hrtoolsServices;
        protected Iuqinger_hrtools_categoryServices _uqinger_hrtools_categoryServices;
        protected Iuqinger_jobsServices _uqinger_jobsServices;
        protected Iuqinger_jobs_contactServices _uqinger_jobs_contactServices;
        protected Iuqinger_jobs_searchServices _uqinger_jobs_searchServices;
        protected Iuqinger_jobs_search_keyServices _uqinger_jobs_search_keyServices;
        protected Iuqinger_jobs_tagServices _uqinger_jobs_tagServices;
        protected Iuqinger_jobs_tmpServices _uqinger_jobs_tmpServices;
        protected Iuqinger_linkServices _uqinger_linkServices;
        protected Iuqinger_link_categoryServices _uqinger_link_categoryServices;
        protected Iuqinger_mail_templatesServices _uqinger_mail_templatesServices;
        protected Iuqinger_mailconfigServices _uqinger_mailconfigServices;
        protected Iuqinger_mailqueueServices _uqinger_mailqueueServices;
        protected Iuqinger_membersServices _uqinger_membersServices;
        protected Iuqinger_members_appealServices _uqinger_members_appealServices;
        protected Iuqinger_members_bindServices _uqinger_members_bindServices;
        protected Iuqinger_members_charge_logServices _uqinger_members_charge_logServices;
        protected Iuqinger_members_handselServices _uqinger_members_handselServices;
        protected Iuqinger_members_infoServices _uqinger_members_infoServices;
        protected Iuqinger_members_logServices _uqinger_members_logServices;
        protected Iuqinger_members_pointsServices _uqinger_members_pointsServices;
        protected Iuqinger_members_setmealServices _uqinger_members_setmealServices;
        protected Iuqinger_members_setmeal_logServices _uqinger_members_setmeal_logServices;
        protected Iuqinger_menuServices _uqinger_menuServices;
        protected Iuqinger_msgServices _uqinger_msgServices;
        protected Iuqinger_navigationServices _uqinger_navigationServices;
        protected Iuqinger_navigation_categoryServices _uqinger_navigation_categoryServices;
        protected Iuqinger_noticeServices _uqinger_noticeServices;
        protected Iuqinger_notice_categoryServices _uqinger_notice_categoryServices;
        protected Iuqinger_oauthServices _uqinger_oauthServices;
        protected Iuqinger_orderServices _uqinger_orderServices;
        protected Iuqinger_order_invoiceServices _uqinger_order_invoiceServices;
        protected Iuqinger_pageServices _uqinger_pageServices;
        protected Iuqinger_paymentServices _uqinger_paymentServices;
        protected Iuqinger_personal_favoritesServices _uqinger_personal_favoritesServices;
        protected Iuqinger_personal_focus_companyServices _uqinger_personal_focus_companyServices;
        protected Iuqinger_personal_jobs_applyServices _uqinger_personal_jobs_applyServices;
        protected Iuqinger_personal_jobs_subscribeServices _uqinger_personal_jobs_subscribeServices;
        protected Iuqinger_personal_service_stickServices _uqinger_personal_service_stickServices;
        protected Iuqinger_personal_service_stick_logServices _uqinger_personal_service_stick_logServices;
        protected Iuqinger_personal_service_tagServices _uqinger_personal_service_tagServices;
        protected Iuqinger_personal_service_tag_categoryServices _uqinger_personal_service_tag_categoryServices;
        protected Iuqinger_personal_service_tag_logServices _uqinger_personal_service_tag_logServices;
        protected Iuqinger_personal_shield_companyServices _uqinger_personal_shield_companyServices;
        protected Iuqinger_pmsServices _uqinger_pmsServices;
        protected Iuqinger_pms_sysServices _uqinger_pms_sysServices;
        protected Iuqinger_promotionServices _uqinger_promotionServices;
        protected Iuqinger_queue_auto_refreshServices _uqinger_queue_auto_refreshServices;
        protected Iuqinger_refresh_logServices _uqinger_refresh_logServices;
        protected Iuqinger_reportServices _uqinger_reportServices;
        protected Iuqinger_report_resumeServices _uqinger_report_resumeServices;
        protected Iuqinger_resumeServices _uqinger_resumeServices;
        protected Iuqinger_resume_credentServices _uqinger_resume_credentServices;
        protected Iuqinger_resume_educationServices _uqinger_resume_educationServices;
        protected Iuqinger_resume_entrustServices _uqinger_resume_entrustServices;
        protected Iuqinger_resume_imgServices _uqinger_resume_imgServices;
        protected Iuqinger_resume_languageServices _uqinger_resume_languageServices;
        protected Iuqinger_resume_outwardServices _uqinger_resume_outwardServices;
        protected Iuqinger_resume_search_fullServices _uqinger_resume_search_fullServices;
        protected Iuqinger_resume_search_preciseServices _uqinger_resume_search_preciseServices;
        protected Iuqinger_resume_tplServices _uqinger_resume_tplServices;
        protected Iuqinger_resume_trainingServices _uqinger_resume_trainingServices;
        protected Iuqinger_resume_workServices _uqinger_resume_workServices;
        protected Iuqinger_setmealServices _uqinger_setmealServices;
        protected Iuqinger_setmeal_incrementServices _uqinger_setmeal_incrementServices;
        protected Iuqinger_smsServices _uqinger_smsServices;
        protected Iuqinger_sms_configServices _uqinger_sms_configServices;
        protected Iuqinger_sms_oauthServices _uqinger_sms_oauthServices;
        protected Iuqinger_sms_templatesServices _uqinger_sms_templatesServices;
        protected Iuqinger_smsqueueServices _uqinger_smsqueueServices;
        protected Iuqinger_sys_email_logServices _uqinger_sys_email_logServices;
        protected Iuqinger_syslogServices _uqinger_syslogServices;
        protected Iuqinger_taskServices _uqinger_taskServices;
        protected Iuqinger_task_logServices _uqinger_task_logServices;
        protected Iuqinger_textServices _uqinger_textServices;
        protected Iuqinger_tplServices _uqinger_tplServices;
        protected Iuqinger_uc_configServices _uqinger_uc_configServices;
        protected Iuqinger_view_jobsServices _uqinger_view_jobsServices;
        protected Iuqinger_view_resumeServices _uqinger_view_resumeServices;
        protected Iuqinger_admin_authServices _uqinger_admin_authServices;
        protected Iuqinger_members_msgtipServices _uqinger_members_msgtipServices;
    }
}
