//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。 
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YQWEntities : DbContext
    {
        public YQWEntities()
            : base("name=YQWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CareerPlanning> CareerPlannings { get; set; }
        public DbSet<ChannelCnvestment> ChannelCnvestments { get; set; }
        public DbSet<ChatReacord> ChatReacords { get; set; }
        public DbSet<CooperativePartner> CooperativePartners { get; set; }
        public DbSet<FeedBack> FeedBacks { get; set; }
        public DbSet<FriendApply> FriendApplies { get; set; }
        public DbSet<Friend> Friends { get; set; }
        public DbSet<JobTraining> JobTrainings { get; set; }
        public DbSet<OrderTime> OrderTimes { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<Person_BlackList> Person_BlackList { get; set; }
        public DbSet<Person_Collection> Person_Collection { get; set; }
        public DbSet<Person_Evaluate> Person_Evaluate { get; set; }
        public DbSet<Person_ExpectWork> Person_ExpectWork { get; set; }
        public DbSet<Person_Follow> Person_Follow { get; set; }
        public DbSet<Person_Message> Person_Message { get; set; }
        public DbSet<Person_PayCheck> Person_PayCheck { get; set; }
        public DbSet<Person_Project> Person_Project { get; set; }
        public DbSet<Person_Report> Person_Report { get; set; }
        public DbSet<Person_Representations> Person_Representations { get; set; }
        public DbSet<Person_Reward> Person_Reward { get; set; }
        public DbSet<Person_Reward_Matching> Person_Reward_Matching { get; set; }
        public DbSet<Person_Skill> Person_Skill { get; set; }
        public DbSet<Person_Test> Person_Test { get; set; }
        public DbSet<Person_Work> Person_Work { get; set; }
        public DbSet<PostInfo> PostInfoes { get; set; }
        public DbSet<PostType> PostTypes { get; set; }
        public DbSet<PresentApplication> PresentApplications { get; set; }
        public DbSet<PresentApplication_Batch> PresentApplication_Batch { get; set; }
        public DbSet<Reward_Order> Reward_Order { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<ServerUser> ServerUsers { get; set; }
        public DbSet<ServerUser_BlackList> ServerUser_BlackList { get; set; }
        public DbSet<ServerUser_Collection> ServerUser_Collection { get; set; }
        public DbSet<ServerUser_Education> ServerUser_Education { get; set; }
        public DbSet<ServerUser_Evaluate> ServerUser_Evaluate { get; set; }
        public DbSet<ServerUser_Follow> ServerUser_Follow { get; set; }
        public DbSet<ServerUser_Message> ServerUser_Message { get; set; }
        public DbSet<ServerUser_Post> ServerUser_Post { get; set; }
        public DbSet<ServerUser_Report> ServerUser_Report { get; set; }
        public DbSet<ServerUser_Tag> ServerUser_Tag { get; set; }
        public DbSet<ServerUser_Work> ServerUser_Work { get; set; }
        public DbSet<Sys_Logs> Sys_Logs { get; set; }
        public DbSet<TransactionRecord> TransactionRecords { get; set; }
        public DbSet<User_Managers> User_Managers { get; set; }
        public DbSet<WelfareTag> WelfareTags { get; set; }
        public DbSet<aTemp> aTemps { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<NewsType> NewsTypes { get; set; }
        public DbSet<Person_Education> Person_Education { get; set; }
        public DbSet<PhoneCode> PhoneCodes { get; set; }
        public DbSet<sys_City> sys_City { get; set; }
        public DbSet<View_News> View_News { get; set; }
        public DbSet<View_Person_Evaluate> View_Person_Evaluate { get; set; }
        public DbSet<View_Person_Order> View_Person_Order { get; set; }
        public DbSet<View_PersonFriend> View_PersonFriend { get; set; }
        public DbSet<View_PersonFriendApply> View_PersonFriendApply { get; set; }
        public DbSet<View_Representations> View_Representations { get; set; }
        public DbSet<View_Reward_Order> View_Reward_Order { get; set; }
        public DbSet<View_RewardList> View_RewardList { get; set; }
        public DbSet<View_SerUser_Reward_Mat_Post> View_SerUser_Reward_Mat_Post { get; set; }
        public DbSet<View_SerUserFriend> View_SerUserFriend { get; set; }
        public DbSet<View_SerUserOrderDetail> View_SerUserOrderDetail { get; set; }
        public DbSet<View_SerUserRewardDetail> View_SerUserRewardDetail { get; set; }
        public DbSet<View_SerUserReword> View_SerUserReword { get; set; }
        public DbSet<View_ServerUser_Evaluate> View_ServerUser_Evaluate { get; set; }
        public DbSet<View_ServerUser_Post> View_ServerUser_Post { get; set; }
        public DbSet<View_ServerUserFriendApply> View_ServerUserFriendApply { get; set; }
        public DbSet<View_SysLog> View_SysLog { get; set; }
        public DbSet<View_User_Managers> View_User_Managers { get; set; }
        public DbSet<WorkPostFilterInfo> WorkPostFilterInfoes { get; set; }
        public DbSet<WorkPostFilterType> WorkPostFilterTypes { get; set; }
        public DbSet<View_WorkPostFilterInfo> View_WorkPostFilterInfo { get; set; }
        public DbSet<View_CompnayInfo> View_CompnayInfo { get; set; }
        public DbSet<View_PersonInfo> View_PersonInfo { get; set; }
        public DbSet<View_ServerUserInfo> View_ServerUserInfo { get; set; }
        public DbSet<View_NewsestRecruit> View_NewsestRecruit { get; set; }
    }
}
