//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wuqingerEntities : DbContext
    {
        public wuqingerEntities()
            : base("name=wuqingerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<qs_applyifo> qs_applyifo { get; set; }
        public DbSet<qs_applyinfo> qs_applyinfo { get; set; }
        public DbSet<uqinger_ad> uqinger_ad { get; set; }
        public DbSet<uqinger_ad_category> uqinger_ad_category { get; set; }
        public DbSet<uqinger_admin> uqinger_admin { get; set; }
        public DbSet<uqinger_admin_auth_group> uqinger_admin_auth_group { get; set; }
        public DbSet<uqinger_admin_log> uqinger_admin_log { get; set; }
        public DbSet<uqinger_admin_role> uqinger_admin_role { get; set; }
        public DbSet<uqinger_apply> uqinger_apply { get; set; }
        public DbSet<uqinger_applyinfo> uqinger_applyinfo { get; set; }
        public DbSet<uqinger_article> uqinger_article { get; set; }
        public DbSet<uqinger_article_category> uqinger_article_category { get; set; }
        public DbSet<uqinger_article_property> uqinger_article_property { get; set; }
        public DbSet<uqinger_audit_reason> uqinger_audit_reason { get; set; }
        public DbSet<uqinger_badword> uqinger_badword { get; set; }
        public DbSet<uqinger_baidu_submiturl> uqinger_baidu_submiturl { get; set; }
        public DbSet<uqinger_baiduxml> uqinger_baiduxml { get; set; }
        public DbSet<uqinger_category> uqinger_category { get; set; }
        public DbSet<uqinger_category_district> uqinger_category_district { get; set; }
        public DbSet<uqinger_category_group> uqinger_category_group { get; set; }
        public DbSet<uqinger_category_jobs> uqinger_category_jobs { get; set; }
        public DbSet<uqinger_category_major> uqinger_category_major { get; set; }
        public DbSet<uqinger_company_down_resume> uqinger_company_down_resume { get; set; }
        public DbSet<uqinger_company_favorites> uqinger_company_favorites { get; set; }
        public DbSet<uqinger_company_img> uqinger_company_img { get; set; }
        public DbSet<uqinger_company_interview> uqinger_company_interview { get; set; }
        public DbSet<uqinger_company_praise> uqinger_company_praise { get; set; }
        public DbSet<uqinger_company_profile> uqinger_company_profile { get; set; }
        public DbSet<uqinger_company_statistics> uqinger_company_statistics { get; set; }
        public DbSet<uqinger_company_tpl> uqinger_company_tpl { get; set; }
        public DbSet<uqinger_config> uqinger_config { get; set; }
        public DbSet<uqinger_consultant> uqinger_consultant { get; set; }
        public DbSet<uqinger_consultant_complaint> uqinger_consultant_complaint { get; set; }
        public DbSet<uqinger_crons> uqinger_crons { get; set; }
        public DbSet<uqinger_explain> uqinger_explain { get; set; }
        public DbSet<uqinger_explain_category> uqinger_explain_category { get; set; }
        public DbSet<uqinger_feedback> uqinger_feedback { get; set; }
        public DbSet<uqinger_help> uqinger_help { get; set; }
        public DbSet<uqinger_help_category> uqinger_help_category { get; set; }
        public DbSet<uqinger_hotword> uqinger_hotword { get; set; }
        public DbSet<uqinger_hrtools> uqinger_hrtools { get; set; }
        public DbSet<uqinger_hrtools_category> uqinger_hrtools_category { get; set; }
        public DbSet<uqinger_jobs> uqinger_jobs { get; set; }
        public DbSet<uqinger_jobs_contact> uqinger_jobs_contact { get; set; }
        public DbSet<uqinger_jobs_search> uqinger_jobs_search { get; set; }
        public DbSet<uqinger_jobs_search_key> uqinger_jobs_search_key { get; set; }
        public DbSet<uqinger_jobs_tag> uqinger_jobs_tag { get; set; }
        public DbSet<uqinger_jobs_tmp> uqinger_jobs_tmp { get; set; }
        public DbSet<uqinger_link> uqinger_link { get; set; }
        public DbSet<uqinger_link_category> uqinger_link_category { get; set; }
        public DbSet<uqinger_mail_templates> uqinger_mail_templates { get; set; }
        public DbSet<uqinger_mailconfig> uqinger_mailconfig { get; set; }
        public DbSet<uqinger_mailqueue> uqinger_mailqueue { get; set; }
        public DbSet<uqinger_members> uqinger_members { get; set; }
        public DbSet<uqinger_members_appeal> uqinger_members_appeal { get; set; }
        public DbSet<uqinger_members_bind> uqinger_members_bind { get; set; }
        public DbSet<uqinger_members_charge_log> uqinger_members_charge_log { get; set; }
        public DbSet<uqinger_members_handsel> uqinger_members_handsel { get; set; }
        public DbSet<uqinger_members_info> uqinger_members_info { get; set; }
        public DbSet<uqinger_members_log> uqinger_members_log { get; set; }
        public DbSet<uqinger_members_points> uqinger_members_points { get; set; }
        public DbSet<uqinger_members_setmeal> uqinger_members_setmeal { get; set; }
        public DbSet<uqinger_members_setmeal_log> uqinger_members_setmeal_log { get; set; }
        public DbSet<uqinger_menu> uqinger_menu { get; set; }
        public DbSet<uqinger_msg> uqinger_msg { get; set; }
        public DbSet<uqinger_navigation> uqinger_navigation { get; set; }
        public DbSet<uqinger_navigation_category> uqinger_navigation_category { get; set; }
        public DbSet<uqinger_notice> uqinger_notice { get; set; }
        public DbSet<uqinger_notice_category> uqinger_notice_category { get; set; }
        public DbSet<uqinger_oauth> uqinger_oauth { get; set; }
        public DbSet<uqinger_order> uqinger_order { get; set; }
        public DbSet<uqinger_order_invoice> uqinger_order_invoice { get; set; }
        public DbSet<uqinger_page> uqinger_page { get; set; }
        public DbSet<uqinger_payment> uqinger_payment { get; set; }
        public DbSet<uqinger_personal_favorites> uqinger_personal_favorites { get; set; }
        public DbSet<uqinger_personal_focus_company> uqinger_personal_focus_company { get; set; }
        public DbSet<uqinger_personal_jobs_apply> uqinger_personal_jobs_apply { get; set; }
        public DbSet<uqinger_personal_jobs_subscribe> uqinger_personal_jobs_subscribe { get; set; }
        public DbSet<uqinger_personal_service_stick> uqinger_personal_service_stick { get; set; }
        public DbSet<uqinger_personal_service_stick_log> uqinger_personal_service_stick_log { get; set; }
        public DbSet<uqinger_personal_service_tag> uqinger_personal_service_tag { get; set; }
        public DbSet<uqinger_personal_service_tag_category> uqinger_personal_service_tag_category { get; set; }
        public DbSet<uqinger_personal_service_tag_log> uqinger_personal_service_tag_log { get; set; }
        public DbSet<uqinger_personal_shield_company> uqinger_personal_shield_company { get; set; }
        public DbSet<uqinger_pms> uqinger_pms { get; set; }
        public DbSet<uqinger_pms_sys> uqinger_pms_sys { get; set; }
        public DbSet<uqinger_promotion> uqinger_promotion { get; set; }
        public DbSet<uqinger_queue_auto_refresh> uqinger_queue_auto_refresh { get; set; }
        public DbSet<uqinger_refresh_log> uqinger_refresh_log { get; set; }
        public DbSet<uqinger_report> uqinger_report { get; set; }
        public DbSet<uqinger_report_resume> uqinger_report_resume { get; set; }
        public DbSet<uqinger_resume> uqinger_resume { get; set; }
        public DbSet<uqinger_resume_credent> uqinger_resume_credent { get; set; }
        public DbSet<uqinger_resume_education> uqinger_resume_education { get; set; }
        public DbSet<uqinger_resume_entrust> uqinger_resume_entrust { get; set; }
        public DbSet<uqinger_resume_img> uqinger_resume_img { get; set; }
        public DbSet<uqinger_resume_language> uqinger_resume_language { get; set; }
        public DbSet<uqinger_resume_outward> uqinger_resume_outward { get; set; }
        public DbSet<uqinger_resume_search_full> uqinger_resume_search_full { get; set; }
        public DbSet<uqinger_resume_search_precise> uqinger_resume_search_precise { get; set; }
        public DbSet<uqinger_resume_tpl> uqinger_resume_tpl { get; set; }
        public DbSet<uqinger_resume_training> uqinger_resume_training { get; set; }
        public DbSet<uqinger_resume_work> uqinger_resume_work { get; set; }
        public DbSet<uqinger_setmeal> uqinger_setmeal { get; set; }
        public DbSet<uqinger_setmeal_increment> uqinger_setmeal_increment { get; set; }
        public DbSet<uqinger_sms> uqinger_sms { get; set; }
        public DbSet<uqinger_sms_config> uqinger_sms_config { get; set; }
        public DbSet<uqinger_sms_oauth> uqinger_sms_oauth { get; set; }
        public DbSet<uqinger_sms_templates> uqinger_sms_templates { get; set; }
        public DbSet<uqinger_smsqueue> uqinger_smsqueue { get; set; }
        public DbSet<uqinger_sys_email_log> uqinger_sys_email_log { get; set; }
        public DbSet<uqinger_syslog> uqinger_syslog { get; set; }
        public DbSet<uqinger_task> uqinger_task { get; set; }
        public DbSet<uqinger_task_log> uqinger_task_log { get; set; }
        public DbSet<uqinger_text> uqinger_text { get; set; }
        public DbSet<uqinger_tpl> uqinger_tpl { get; set; }
        public DbSet<uqinger_uc_config> uqinger_uc_config { get; set; }
        public DbSet<uqinger_view_jobs> uqinger_view_jobs { get; set; }
        public DbSet<uqinger_view_resume> uqinger_view_resume { get; set; }
        public DbSet<uqinger_admin_auth> uqinger_admin_auth { get; set; }
        public DbSet<uqinger_members_msgtip> uqinger_members_msgtip { get; set; }
    }
}
