//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_Reward_Matching
    {
        public int PerRewMatID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> PerID { get; set; }
        public Nullable<int> PerRewID { get; set; }
        public Nullable<int> SerUserID { get; set; }
        public Nullable<int> SerPostID { get; set; }
        public Nullable<System.DateTime> MatchingTime { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> RefTime { get; set; }
        public Nullable<int> IsDelete { get; set; }
    }
}
