//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_ExpectWork
    {
        public int PerExID { get; set; }
        public Nullable<int> PerID { get; set; }
        public string ExpectedPostion { get; set; }
        public string WorkType { get; set; }
        public string ExCity { get; set; }
        public string ExSalary { get; set; }
        public string ReMark { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Colvalue { get; set; }
    }
}
