//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class qs_applyinfo
    {
        public int id { get; set; }
        public int jobid { get; set; }
        public int userid { get; set; }
        public string name { get; set; }
        public bool sex { get; set; }
        public string age { get; set; }
        public string address { get; set; }
        public string education { get; set; }
        public string year { get; set; }
        public string phone { get; set; }
        public bool view { get; set; }
        public int addtime { get; set; }
        public bool state { get; set; }
    }
}
