//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class uqinger_payment
    {
        public long id { get; set; }
        public long listorder { get; set; }
        public string typename { get; set; }
        public string byname { get; set; }
        public string p_introduction { get; set; }
        public string notes { get; set; }
        public string partnerid { get; set; }
        public string ytauthkey { get; set; }
        public string fee { get; set; }
        public string parameter1 { get; set; }
        public string parameter2 { get; set; }
        public string parameter3 { get; set; }
        public byte p_install { get; set; }
    }
}
