//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class uqinger_personal_jobs_subscribe
    {
        public int id { get; set; }
        public int uid { get; set; }
        public string title { get; set; }
        public string key { get; set; }
        public int trade { get; set; }
        public string trade_cn { get; set; }
        public string intention_jobs_id { get; set; }
        public string intention_jobs { get; set; }
        public string district { get; set; }
        public string district_cn { get; set; }
        public int wage { get; set; }
        public string wage_cn { get; set; }
        public string email { get; set; }
        public int addtime { get; set; }
        public int update_time { get; set; }
        public bool status { get; set; }
    }
}
