//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class uqinger_members_handsel
    {
        public int id { get; set; }
        public long uid { get; set; }
        public string htype { get; set; }
        public string htype_cn { get; set; }
        public bool operate { get; set; }
        public long points { get; set; }
        public int addtime { get; set; }
    }
}
