//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class uqinger_task
    {
        public long id { get; set; }
        public string title { get; set; }
        public string t_alias { get; set; }
        public long points { get; set; }
        public bool once { get; set; }
        public bool becount { get; set; }
        public sbyte times { get; set; }
        public bool utype { get; set; }
        public bool dayly { get; set; }
    }
}
