//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class uqinger_hrtools
    {
        public long h_id { get; set; }
        public int h_typeid { get; set; }
        public string h_filename { get; set; }
        public string h_fileurl { get; set; }
        public int h_order { get; set; }
        public string h_color { get; set; }
        public bool h_strong { get; set; }
    }
}
