//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class uqinger_mailqueue
    {
        public long m_id { get; set; }
        public byte m_type { get; set; }
        public long m_addtime { get; set; }
        public long m_sendtime { get; set; }
        public long m_uid { get; set; }
        public string m_mail { get; set; }
        public string m_subject { get; set; }
        public string m_body { get; set; }
    }
}
