//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class uqinger_members_setmeal
    {
        public long id { get; set; }
        public bool expire { get; set; }
        public long uid { get; set; }
        public long setmeal_id { get; set; }
        public string setmeal_name { get; set; }
        public long days { get; set; }
        public long expense { get; set; }
        public long jobs_meanwhile { get; set; }
        public long refresh_jobs_free { get; set; }
        public long download_resume { get; set; }
        public long download_resume_max { get; set; }
        public string added { get; set; }
        public long starttime { get; set; }
        public long endtime { get; set; }
        public string setmeal_img { get; set; }
        public bool show_apply_contact { get; set; }
        public bool is_free { get; set; }
    }
}
