//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class uqinger_setmeal_increment
    {
        public long id { get; set; }
        public string cat { get; set; }
        public string name { get; set; }
        public long value { get; set; }
        public string price { get; set; }
        public long sort { get; set; }
    }
}
