//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class uqinger_promotion
    {
        public long cp_id { get; set; }
        public long cp_uid { get; set; }
        public string cp_ptype { get; set; }
        public long cp_jobid { get; set; }
        public long cp_days { get; set; }
        public long cp_starttime { get; set; }
        public long cp_endtime { get; set; }
    }
}
