//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class uqinger_navigation
    {
        public long id { get; set; }
        public string alias { get; set; }
        public byte urltype { get; set; }
        public byte display { get; set; }
        public string title { get; set; }
        public string color { get; set; }
        public string pagealias { get; set; }
        public string list_id { get; set; }
        public string tag { get; set; }
        public string url { get; set; }
        public string target { get; set; }
        public long navigationorder { get; set; }
        public bool is_personal { get; set; }
    }
}
