//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class uqinger_company_profile
    {
        public long id { get; set; }
        public long uid { get; set; }
        public string tpl { get; set; }
        public string companyname { get; set; }
        public int nature { get; set; }
        public string nature_cn { get; set; }
        public int trade { get; set; }
        public string trade_cn { get; set; }
        public int district { get; set; }
        public int sdistrict { get; set; }
        public int tdistrict { get; set; }
        public string district_cn { get; set; }
        public int street { get; set; }
        public string street_cn { get; set; }
        public int scale { get; set; }
        public string scale_cn { get; set; }
        public string registered { get; set; }
        public string currency { get; set; }
        public string address { get; set; }
        public string contact { get; set; }
        public string telephone { get; set; }
        public string landline_tel { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string companyname_full { get; set; }
        public string legal_person { get; set; }
        public string license { get; set; }
        public string certificate_img { get; set; }
        public string logo { get; set; }
        public string contents { get; set; }
        public int setmeal_id { get; set; }
        public string setmeal_name { get; set; }
        public byte audit { get; set; }
        public byte map_open { get; set; }
        public decimal map_x { get; set; }
        public decimal map_y { get; set; }
        public byte map_zoom { get; set; }
        public long addtime { get; set; }
        public long refreshtime { get; set; }
        public long click { get; set; }
        public byte user_status { get; set; }
        public bool contact_show { get; set; }
        public bool telephone_show { get; set; }
        public bool email_show { get; set; }
        public bool landline_tel_show { get; set; }
        public byte robot { get; set; }
        public long comment { get; set; }
        public sbyte resume_processing { get; set; }
        public string tag { get; set; }
        public bool wzp_tpl { get; set; }
        public long jobs { get; set; }
        public long replys { get; set; }
        public bool famous { get; set; }
        public string qq { get; set; }
    }
}
