//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class uqinger_syslog
    {
        public long l_id { get; set; }
        public bool l_type { get; set; }
        public string l_type_name { get; set; }
        public long l_time { get; set; }
        public string l_ip { get; set; }
        public string l_address { get; set; }
        public string l_page { get; set; }
        public string l_str { get; set; }
    }
}
