//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class uqinger_members
    {
        public long uid { get; set; }
        public bool utype { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public bool email_audit { get; set; }
        public string mobile { get; set; }
        public bool mobile_audit { get; set; }
        public string password { get; set; }
        public string pwd_hash { get; set; }
        public long reg_time { get; set; }
        public string reg_ip { get; set; }
        public string reg_address { get; set; }
        public long last_login_time { get; set; }
        public string last_login_ip { get; set; }
        public byte status { get; set; }
        public string avatars { get; set; }
        public byte robot { get; set; }
        public int consultant { get; set; }
        public Nullable<long> remind_email_time { get; set; }
        public string imei { get; set; }
        public int sms_num { get; set; }
        public bool reg_type { get; set; }
        public byte remind_email_ex_time { get; set; }
        public string invitation_code { get; set; }
    }
}
