//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class uqinger_company_statistics
    {
        public long id { get; set; }
        public long comid { get; set; }
        public long uid { get; set; }
        public bool source { get; set; }
        public long jobid { get; set; }
        public bool apply { get; set; }
        public long addtime { get; set; }
        public long viewtime { get; set; }
    }
}
