//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class uqinger_jobs_tmp
    {
        public long id { get; set; }
        public long uid { get; set; }
        public string jobs_name { get; set; }
        public string companyname { get; set; }
        public long company_id { get; set; }
        public long company_addtime { get; set; }
        public bool company_audit { get; set; }
        public bool emergency { get; set; }
        public bool stick { get; set; }
        public long nature { get; set; }
        public string nature_cn { get; set; }
        public bool sex { get; set; }
        public string sex_cn { get; set; }
        public string age { get; set; }
        public int amount { get; set; }
        public int topclass { get; set; }
        public int category { get; set; }
        public int subclass { get; set; }
        public string category_cn { get; set; }
        public int trade { get; set; }
        public string trade_cn { get; set; }
        public int scale { get; set; }
        public string scale_cn { get; set; }
        public int district { get; set; }
        public int sdistrict { get; set; }
        public int tdistrict { get; set; }
        public string district_cn { get; set; }
        public string tag { get; set; }
        public string tag_cn { get; set; }
        public int education { get; set; }
        public string education_cn { get; set; }
        public int experience { get; set; }
        public string experience_cn { get; set; }
        public int minwage { get; set; }
        public int maxwage { get; set; }
        public bool negotiable { get; set; }
        public string contents { get; set; }
        public long addtime { get; set; }
        public long deadline { get; set; }
        public long refreshtime { get; set; }
        public int stime { get; set; }
        public long setmeal_deadline { get; set; }
        public int setmeal_id { get; set; }
        public string setmeal_name { get; set; }
        public bool audit { get; set; }
        public bool display { get; set; }
        public long click { get; set; }
        public string key { get; set; }
        public bool user_status { get; set; }
        public bool robot { get; set; }
        public string tpl { get; set; }
        public decimal map_x { get; set; }
        public decimal map_y { get; set; }
        public byte map_zoom { get; set; }
        public bool add_mode { get; set; }
        public bool is_entrust { get; set; }
        public string department { get; set; }
        public bool famous { get; set; }
    }
}
