//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class uqinger_personal_jobs_apply
    {
        public long did { get; set; }
        public long resume_id { get; set; }
        public string resume_name { get; set; }
        public long personal_uid { get; set; }
        public long jobs_id { get; set; }
        public string jobs_name { get; set; }
        public long company_id { get; set; }
        public string company_name { get; set; }
        public long company_uid { get; set; }
        public long apply_addtime { get; set; }
        public byte personal_look { get; set; }
        public string notes { get; set; }
        public bool is_reply { get; set; }
        public bool is_apply { get; set; }
        public int reply_time { get; set; }
    }
}
