//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class uqinger_admin_auth_group
    {
        public int id { get; set; }
        public string name { get; set; }
        public int mid { get; set; }
        public int msid { get; set; }
        public string mids { get; set; }
        public string remark { get; set; }
        public int ordid { get; set; }
        public int addtime { get; set; }
        public int update_time { get; set; }
    }
}
