//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class uqinger_resume
    {
        public long id { get; set; }
        public long uid { get; set; }
        public byte display { get; set; }
        public byte display_name { get; set; }
        public byte audit { get; set; }
        public bool stick { get; set; }
        public long strong_tag { get; set; }
        public string title { get; set; }
        public string fullname { get; set; }
        public byte sex { get; set; }
        public string sex_cn { get; set; }
        public long nature { get; set; }
        public string nature_cn { get; set; }
        public string trade { get; set; }
        public string trade_cn { get; set; }
        public int birthdate { get; set; }
        public string residence { get; set; }
        public string height { get; set; }
        public byte marriage { get; set; }
        public string marriage_cn { get; set; }
        public short experience { get; set; }
        public string experience_cn { get; set; }
        public string district { get; set; }
        public string district_cn { get; set; }
        public int wage { get; set; }
        public string wage_cn { get; set; }
        public string householdaddress { get; set; }
        public int education { get; set; }
        public string education_cn { get; set; }
        public short major { get; set; }
        public string major_cn { get; set; }
        public string tag { get; set; }
        public string tag_cn { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public bool email_notify { get; set; }
        public string intention_jobs_id { get; set; }
        public string intention_jobs { get; set; }
        public string specialty { get; set; }
        public bool photo { get; set; }
        public string photo_img { get; set; }
        public bool photo_audit { get; set; }
        public bool photo_display { get; set; }
        public long addtime { get; set; }
        public long refreshtime { get; set; }
        public int stime { get; set; }
        public byte entrust { get; set; }
        public bool talent { get; set; }
        public bool level { get; set; }
        public byte complete_percent { get; set; }
        public int current { get; set; }
        public string current_cn { get; set; }
        public string word_resume { get; set; }
        public string word_resume_title { get; set; }
        public long word_resume_addtime { get; set; }
        public string key_full { get; set; }
        public string key_precise { get; set; }
        public long click { get; set; }
        public string tpl { get; set; }
        public bool resume_from_pc { get; set; }
        public bool def { get; set; }
        public bool mobile_audit { get; set; }
    }
}
