//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class uqinger_admin_log
    {
        public long log_id { get; set; }
        public string admin_name { get; set; }
        public int add_time { get; set; }
        public string log_value { get; set; }
        public string log_ip { get; set; }
        public bool log_type { get; set; }
    }
}
