//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Reward_Order
    {
        public int OrderID { get; set; }
        public string OrderNum { get; set; }
        public Nullable<int> PerRewardID { get; set; }
        public Nullable<int> PostID { get; set; }
        public Nullable<decimal> RewardMoney { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> OrderState { get; set; }
        public Nullable<int> PerID { get; set; }
        public Nullable<int> SerUserID { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public string SerRealName { get; set; }
        public string EngagePost { get; set; }
        public string PostName { get; set; }
        public string PerRealName { get; set; }
    }
}
