//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CompnayInfo
    {
        public Nullable<long> Thelevel { get; set; }
        public int SerUserID { get; set; }
        public string RealName { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string PhotoImg { get; set; }
        public string Trade { get; set; }
        public string Company { get; set; }
        public string Position { get; set; }
        public string WorkCity { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Describe { get; set; }
        public string IDCardImg { get; set; }
        public Nullable<System.DateTime> IDCardTime { get; set; }
        public Nullable<int> Flag { get; set; }
        public string SerImg { get; set; }
        public Nullable<System.DateTime> SerTime { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public string Password { get; set; }
        public Nullable<int> IDCardState { get; set; }
        public Nullable<int> SerImgState { get; set; }
        public string ImOpenID { get; set; }
        public string WxOpenID { get; set; }
        public Nullable<int> PerID { get; set; }
        public string QQOpenID { get; set; }
        public string WbOpenID { get; set; }
        public Nullable<int> AttestType { get; set; }
        public string DevelopProspect { get; set; }
        public string Scale { get; set; }
        public string Nature { get; set; }
        public Nullable<int> recruitPostCount { get; set; }
    }
}
