//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
     
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class aTempView
    {
        public int ID { get; set; }
        public string 编号 { get; set; }
        public string 来源 { get; set; }
        public string 姓名 { get; set; }
        public string 籍贯 { get; set; }
        public string 性别 { get; set; }
        public string 年龄 { get; set; }
        public string 毕业学校 { get; set; }
        public string 毕业时间 { get; set; }
        public string 学历 { get; set; }
        public string 专业 { get; set; }
        public string 电话 { get; set; }
        public string 工作年限 { get; set; }
        public string 求职意向 { get; set; }
        public string 状态 { get; set; }
        public string 备注 { get; set; }
        public string 邮箱 { get; set; }
        public string 职位名称 { get; set; }
        public string 职位类型 { get; set; }
        public string 期望城市 { get; set; }
        public string 期望月薪 { get; set; }
        public string 公司名称 { get; set; }
        public string 职位 { get; set; }
        public string 入职时间至离职时间 { get; set; }
        public string 离职时间 { get; set; }
        public string 工作内容 { get; set; }
        public string 自我评价 { get; set; }
        public Nullable<int> PerID { get; set; }
        public Nullable<int> PerRewardID { get; set; }
    }
}
