//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
     
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CareerPlanningView
    {
        public int CPID { get; set; }
        public string CPType { get; set; }
        public string CPName { get; set; }
        public string CPTitle { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CPDes { get; set; }
        public Nullable<int> Sort { get; set; }
        public string ImgUrl { get; set; }
        public string AbsDes { get; set; }
    }
}
