//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
     
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ChannelCnvestmentView
    {
        public int ID { get; set; }
        public string Company { get; set; }
        public string Address { get; set; }
        public string LinkMan { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string MainBusiness { get; set; }
        public string City { get; set; }
        public string TeamSize { get; set; }
        public string MainAdvantage { get; set; }
    }
}
