//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
     
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Person_EvaluateView
    {
        public int ID { get; set; }
        public Nullable<int> PerID { get; set; }
        public string PerName { get; set; }
        public string EvaluateCon { get; set; }
        public Nullable<System.DateTime> EvaluateTime { get; set; }
        public Nullable<int> EvaluateUserID { get; set; }
        public string EvaluateName { get; set; }
        public Nullable<int> EvaLevel { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> EvaluateType { get; set; }
    }
}
