//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Person_ProjectView
    {
        public int PerProID { get; set; }
        public Nullable<int> PerID { get; set; }
        public string ProName { get; set; }
        public string ProDuty { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string ProDes { get; set; }
        public string ProLink { get; set; }
        public string Colvalue { get; set; }
    }
}
