//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
     
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PersonView
    {
        public int PerID { get; set; }
        public string RealName { get; set; }
        public string Phne { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string Education { get; set; }
        public string WorkLife { get; set; }
        public string Birth { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string OneDes { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Flag { get; set; }
        public string AuthImg { get; set; }
        public Nullable<System.DateTime> AuthTime { get; set; }
        public string MyDes { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public string PhoneCode { get; set; }
        public Nullable<System.DateTime> CodeTime { get; set; }
        public string ImOpenID { get; set; }
        public string WxOpenID { get; set; }
        public Nullable<int> SerUserID { get; set; }
        public string QQOpenID { get; set; }
        public string WbOpenID { get; set; }
    }
}
