//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Person_RewardView
    {
        public int PerRewardID { get; set; }
        public Nullable<int> PerID { get; set; }
        public string Trade { get; set; }
        public string CompanySize { get; set; }
        public string CompanyNature { get; set; }
        public string EngagePost { get; set; }
        public string DemandPay { get; set; }
        public string JobCity { get; set; }
        public string OtherDemand { get; set; }
        public string CompanyMatching { get; set; }
        public string OtherDemandDes { get; set; }
        public Nullable<decimal> RewardMoney { get; set; }
        public Nullable<System.DateTime> RewardTime { get; set; }
        public Nullable<int> RewardState { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public string Education { get; set; }
        public string WorkLife { get; set; }
    }
}
