//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
     
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ServerUser_PostView
    {
        public int SerUserPostID { get; set; }
        public Nullable<int> SerUserID { get; set; }
        public string Company { get; set; }
        public string Trade { get; set; }
        public string Scale { get; set; }
        public string Nature { get; set; }
        public string PostName { get; set; }
        public string PostDuty { get; set; }
        public string Salary { get; set; }
        public string DevelopProspect { get; set; }
        public string DirectLeader { get; set; }
        public string WorkAdress { get; set; }
        public string Address { get; set; }
        public string WelfareTag { get; set; }
        public string CompanyMatching { get; set; }
        public string OtherPoint { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Colvalue { get; set; }
        public Nullable<int> IsSole { get; set; }
        public string ComImg { get; set; }
        public Nullable<int> SeeCount { get; set; }
    }
}
