//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class sys_CityView
    {
        public string Code { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string county { get; set; }
        public Nullable<int> CityLevel { get; set; }
        public string CityZip { get; set; }
    }
}
