//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class uqinger_personal_service_tag_logView
    {
        public long id { get; set; }
        public long resume_id { get; set; }
        public long resume_uid { get; set; }
        public long days { get; set; }
        public long points { get; set; }
        public long tag_id { get; set; }
        public long addtime { get; set; }
        public long endtime { get; set; }
    }
}
