//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class uqinger_hrtools_categoryView
    {
        public int c_id { get; set; }
        public string c_name { get; set; }
        public int c_order { get; set; }
        public sbyte c_adminset { get; set; }
        public string c_img { get; set; }
        public string c_desc { get; set; }
    }
}
