//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class uqinger_company_interviewView
    {
        public long did { get; set; }
        public long resume_id { get; set; }
        public string resume_name { get; set; }
        public int resume_addtime { get; set; }
        public long resume_uid { get; set; }
        public long jobs_id { get; set; }
        public string jobs_name { get; set; }
        public int jobs_addtime { get; set; }
        public long company_id { get; set; }
        public string company_name { get; set; }
        public int company_addtime { get; set; }
        public long company_uid { get; set; }
        public long interview_addtime { get; set; }
        public string notes { get; set; }
        public byte personal_look { get; set; }
        public string interview_time { get; set; }
        public string address { get; set; }
        public string contact { get; set; }
        public string telephone { get; set; }
    }
}
