//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class uqinger_menuView
    {
        public long id { get; set; }
        public string name { get; set; }
        public long pid { get; set; }
        public string spid { get; set; }
        public string log_cn { get; set; }
        public string module_name { get; set; }
        public string controller_name { get; set; }
        public string action_name { get; set; }
        public bool menu_type { get; set; }
        public bool is_parent { get; set; }
        public string data { get; set; }
        public string remark { get; set; }
        public bool often { get; set; }
        public long ordid { get; set; }
        public bool display { get; set; }
        public string stat { get; set; }
        public bool sys_set { get; set; }
        public bool mods { get; set; }
    }
}
