//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class uqinger_orderView
    {
        public long id { get; set; }
        public string oid { get; set; }
        public long uid { get; set; }
        public byte utype { get; set; }
        public long order_type { get; set; }
        public bool pay_type { get; set; }
        public byte is_paid { get; set; }
        public decimal amount { get; set; }
        public decimal pay_amount { get; set; }
        public long pay_points { get; set; }
        public string payment { get; set; }
        public string payment_cn { get; set; }
        public string description { get; set; }
        public string service_name { get; set; }
        public long points { get; set; }
        public long setmeal { get; set; }
        public string @params { get; set; }
        public string notes { get; set; }
        public long addtime { get; set; }
        public long payment_time { get; set; }
        public string discount { get; set; }
        public decimal fee { get; set; }
    }
}
