//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class uqinger_jobs_search_keyView
    {
        public long id { get; set; }
        public long uid { get; set; }
        public bool audit { get; set; }
        public bool stick { get; set; }
        public bool emergency { get; set; }
        public long nature { get; set; }
        public bool sex { get; set; }
        public int topclass { get; set; }
        public int category { get; set; }
        public int subclass { get; set; }
        public int trade { get; set; }
        public int district { get; set; }
        public int sdistrict { get; set; }
        public int tdistrict { get; set; }
        public int education { get; set; }
        public int experience { get; set; }
        public long minwage { get; set; }
        public long maxwage { get; set; }
        public int scale { get; set; }
        public long click { get; set; }
        public double map_x { get; set; }
        public double map_y { get; set; }
        public long refreshtime { get; set; }
        public int stime { get; set; }
        public string key { get; set; }
        public int setmeal_id { get; set; }
        public bool license { get; set; }
        public bool famous { get; set; }
    }
}
