//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class uqinger_applyView
    {
        public int id { get; set; }
        public string alias { get; set; }
        public string module_name { get; set; }
        public string version { get; set; }
        public bool is_create_table { get; set; }
        public bool is_insert_data { get; set; }
        public bool is_exe { get; set; }
        public bool is_delete_data { get; set; }
        public string update_time { get; set; }
        public int setup_time { get; set; }
        public string explain { get; set; }
        public string versioning { get; set; }
        public bool status { get; set; }
    }
}
