//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class uqinger_order_invoiceView
    {
        public long order_id { get; set; }
        public long uid { get; set; }
        public bool title { get; set; }
        public bool cid { get; set; }
        public string organization { get; set; }
        public string addressee { get; set; }
        public string mobile { get; set; }
        public string address { get; set; }
        public string postcode { get; set; }
        public bool audit { get; set; }
        public int addtime { get; set; }
    }
}
