//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class uqinger_helpView
    {
        public long id { get; set; }
        public int type_id { get; set; }
        public int parentid { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public long click { get; set; }
        public long addtime { get; set; }
        public long ordid { get; set; }
    }
}
