//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class uqinger_category_districtView
    {
        public long id { get; set; }
        public long parentid { get; set; }
        public string categoryname { get; set; }
        public int category_order { get; set; }
        public string stat_jobs { get; set; }
        public string stat_resume { get; set; }
        public string spell { get; set; }
    }
}
