//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class uqinger_members_infoView
    {
        public long id { get; set; }
        public long uid { get; set; }
        public string realname { get; set; }
        public int sex { get; set; }
        public string sex_cn { get; set; }
        public string birthday { get; set; }
        public string residence { get; set; }
        public int education { get; set; }
        public string education_cn { get; set; }
        public short major { get; set; }
        public string major_cn { get; set; }
        public int experience { get; set; }
        public string experience_cn { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string height { get; set; }
        public string householdaddress { get; set; }
        public int marriage { get; set; }
        public string marriage_cn { get; set; }
        public bool display_name { get; set; }
        public bool photo_audit { get; set; }
        public bool photo_display { get; set; }
        public int resume_num { get; set; }
        public int view_resume_num { get; set; }
        public int interview_num { get; set; }
        public int jobs_num { get; set; }
        public int view_jobs_num { get; set; }
    }
}
