//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class uqinger_pmsView
    {
        public long pmid { get; set; }
        public bool msgtype { get; set; }
        public string msgfrom { get; set; }
        public long msgfromuid { get; set; }
        public long msgtouid { get; set; }
        public string msgtoname { get; set; }
        public string message { get; set; }
        public int dateline { get; set; }
        public bool @new { get; set; }
        public string reply { get; set; }
        public int replytime { get; set; }
        public long replyuid { get; set; }
    }
}
