//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class uqinger_smsqueueView
    {
        public long s_id { get; set; }
        public byte s_type { get; set; }
        public long s_addtime { get; set; }
        public long s_sendtime { get; set; }
        public long s_uid { get; set; }
        public string s_mobile { get; set; }
        public string s_body { get; set; }
    }
}
