//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class View_RepresentationsView
    {
        public int ID { get; set; }
        public Nullable<int> PerID { get; set; }
        public string RealName { get; set; }
        public string OrderNum { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> State { get; set; }
        public string Expr1 { get; set; }
        public string Phne { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<decimal> RewardMoney { get; set; }
    }
}
