//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UQing.Hr.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
     
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class View_SerUserRewardDetailView
    {
        public string RealName { get; set; }
        public string Phne { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string Photo { get; set; }
        public string City { get; set; }
        public string Education { get; set; }
        public string WorkLife { get; set; }
        public string Trade { get; set; }
        public string CompanySize { get; set; }
        public string CompanyNature { get; set; }
        public string EngagePost { get; set; }
        public string DemandPay { get; set; }
        public string JobCity { get; set; }
        public string OtherDemand { get; set; }
        public string CompanyMatching { get; set; }
        public string OtherDemandDes { get; set; }
        public Nullable<decimal> RewardMoney { get; set; }
        public Nullable<System.DateTime> RewardTime { get; set; }
        public int PerRewMatID { get; set; }
        public Nullable<int> PerID { get; set; }
        public Nullable<int> PerRewID { get; set; }
        public Nullable<int> SerUserID { get; set; }
        public Nullable<int> SerPostID { get; set; }
        public Nullable<System.DateTime> MatchingTime { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> RefTime { get; set; }
        public string Company { get; set; }
        public string Expr1 { get; set; }
        public string Scale { get; set; }
        public string Nature { get; set; }
        public string PostName { get; set; }
        public string PostDuty { get; set; }
        public string Salary { get; set; }
        public string DevelopProspect { get; set; }
        public string DirectLeader { get; set; }
        public string WorkAdress { get; set; }
        public string Address { get; set; }
        public string WelfareTag { get; set; }
        public string Expr2 { get; set; }
        public string OtherPoint { get; set; }
        public string Expr3 { get; set; }
        public string Expr4 { get; set; }
    }
}
